// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'api-keys.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: apiKeys.apiKeyWeb, //web api key
    appId: '1:592670576430:web:cf0e2a9fb745567b23b4bf',
    messagingSenderId: '592670576430',
    projectId: 'flutter-qryoklamasistemi',
    authDomain: 'flutter-qryoklamasistemi.firebaseapp.com',
    storageBucket: 'flutter-qryoklamasistemi.appspot.com',
    measurementId: 'G-HEBSLBC8JQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: apiKeys.apiKeyAndroid,
    appId: '1:592670576430:android:7879248019b4d60b23b4bf',
    messagingSenderId: '592670576430',
    projectId: 'flutter-qryoklamasistemi',
    storageBucket: 'flutter-qryoklamasistemi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: apiKeys.apiKeyIOS,
    appId: '1:592670576430:ios:f3ec8f9c01e016ee23b4bf',
    messagingSenderId: '592670576430',
    projectId: 'flutter-qryoklamasistemi',
    storageBucket: 'flutter-qryoklamasistemi.appspot.com',
    iosBundleId: 'com.example.flutterQryoklamasistemi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: apiKeys.apiKeyMacOS,
    appId: '1:592670576430:ios:236a23818f3ab08b23b4bf',
    messagingSenderId: '592670576430',
    projectId: 'flutter-qryoklamasistemi',
    storageBucket: 'flutter-qryoklamasistemi.appspot.com',
    iosBundleId: 'com.example.flutterQryoklamasistemi.RunnerTests',
  );
}
